
CREATE DATABASE DEPTO_EMP;

USE DEPTO_EMP;

CREATE TABLE DEPARTAMENTO(
	IDDEPTO INT NOT NULL PRIMARY KEY,
	NOMEDEPTO VARCHAR(15) NOT NULL,
	GERENTE INT NOT NULL,
	DIVISAO VARCHAR(10) NOT NULL,
	LOCAL VARCHAR(15) NOT NULL
	);


CREATE TABLE EMPREGADO(
	IDEMPREGADO INT NOT NULL PRIMARY KEY,
	NOMEEMPREGADO VARCHAR(20) NOT NULL,
	IDDEPTO INT NOT NULL,
	CARGO VARCHAR(6) NOT NULL,
	TEMPO_EMP INT NULL,
	SALARIO DECIMAL(10, 2) NULL,
	COMISSAO DECIMAL(10, 2) NULL
	);

ALTER TABLE EMPREGADO ADD CONSTRAINT FK_EMPREGADO_DEPTO FOREIGN KEY(IDDEPTO) REFERENCES DEPARTAMENTO (IDDEPTO);

INSERT DEPARTAMENTO (IDDEPTO, NOMEDEPTO, GERENTE, DIVISAO, LOCAL) VALUES (10, 'MATRIZ', 160, 'CENTRO', 'SAO PAULO');
INSERT DEPARTAMENTO (IDDEPTO, NOMEDEPTO, GERENTE, DIVISAO, LOCAL) VALUES (15, 'CAMPINAS', 50, 'SUDESTE', 'CAMPINAS');
INSERT DEPARTAMENTO (IDDEPTO, NOMEDEPTO, GERENTE, DIVISAO, LOCAL) VALUES (20, 'RIO', 10, 'SUDESTE', 'R.JANEIRO');
INSERT DEPARTAMENTO (IDDEPTO, NOMEDEPTO, GERENTE, DIVISAO, LOCAL) VALUES (38, 'MINAS', 30, 'SUDESTE', 'B.HORIZONTE');
INSERT DEPARTAMENTO (IDDEPTO, NOMEDEPTO, GERENTE, DIVISAO, LOCAL) VALUES (42, 'BAHIA', 100, 'NORDESTE', 'SALVADOR');
INSERT DEPARTAMENTO (IDDEPTO, NOMEDEPTO, GERENTE, DIVISAO, LOCAL) VALUES (51, 'RECIFE', 140, 'NORDESTE', 'RECIFE');
INSERT DEPARTAMENTO (IDDEPTO, NOMEDEPTO, GERENTE, DIVISAO, LOCAL) VALUES (84, 'PARANA', 290, 'SUL', 'CURITIBA');

INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (10, 'SANTANA', 20, 'GER', 7, CAST(1835.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (20, 'ORSINI', 20, 'VENDAS', 8, CAST(1817.00 AS DECIMAL(10, 2)), CAST(612.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (30, 'DANTAS', 38, 'GER', 5, CAST(1750.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (40, 'OBRIEN', 38,'VENDAS', 6, CAST(1800.00 AS DECIMAL(10, 2)), CAST(846.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (50,'SOUZA', 15,'GER', 10, CAST(2065.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (60,'SUZUKI', 38,'VENDAS', NULL, CAST(1680.00 AS DECIMAL(10, 2)), CAST(650.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (70,'ALMEIDA', 15,'VENDAS', 7, CAST(1650.00 AS DECIMAL(10, 2)), CAST(1152.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (80,'JAMES', 20,'ATEND', NULL, CAST(1350.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (90,'KOONITZ', 42,'VENDAS', 6, CAST(1800.00 AS DECIMAL(10, 2)), CAST(1386.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (100,'PLOTZ', 42,'GER', 7, CAST(1835.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (110,'NGAN', 15,'ATEND', 5, CAST(1250.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (120,'NAUGHTON', 38,'ATEND', NULL, CAST(1295.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (130,'YAMAGUCHI', 42,'ATEND', 6, CAST(1050.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (140,'FRAYE', 51,'GER', 6, CAST(2115.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (150,'OLIVEIRA', 51,'VENDAS', 6, CAST(1945.00 AS DECIMAL(10, 2)), CAST(637.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (160,'MOLINARI', 10,'GER', 7, CAST(2295.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (170,'KERMISCH', 15,'ATEND', 4, CAST(1225.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (180,'ABRAHAMS', 38,'ATEND', 3, CAST(1200.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (190,'SNEIDER', 20,'ATEND', 8, CAST(1425.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (200,'SCOUTTEN', 42,'ATEND', NULL, CAST(1150.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (210,'LU', 10,'GER', 10, CAST(2001.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (220,'SMITH', 51,'VENDAS', 7, CAST(1765.00 AS DECIMAL(10, 2)), CAST(992.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (230,'LUNDQUIST', 51,'ATEND', 3, CAST(1336.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (240,'DANIELS', 10,'GER', 5, CAST(1926.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (250,'WHEELER', 51,'ATEND', 6, CAST(1446.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (260,'JONES', 10,'GER', 12, CAST(2123.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (270,'LEA', 51,'GER', 9, CAST(1855.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (280,'WILSON', 38,'VENDAS', 9, CAST(1867.00 AS DECIMAL(10, 2)), CAST(811.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (290,'PINHO', 84,'GER', 10, CAST(1981.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (300,'DANIVS', 84,'VENDAS', 5, CAST(1545.00 AS DECIMAL(10, 2)), CAST(806.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (310,'GRAHAM', 38,'VENDAS', 13, CAST(2100.00 AS DECIMAL(10, 2)), CAST(200.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (320,'GONZALES', 20,'VENDAS', 4, CAST(1658.00 AS DECIMAL(10, 2)), CAST(844.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (330,'BURKE', 20,'ATEND', 1, CAST(1098.00 AS DECIMAL(10, 2)), NULL);
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (340,'VIEIRA', 84,'VENDAS', 7, CAST(1784.00 AS DECIMAL(10, 2)), CAST(1285.00 AS DECIMAL(10, 2)));
INSERT EMPREGADO (IDEMPREGADO, NOMEEMPREGADO, IDDEPTO, CARGO, TEMPO_EMP, SALARIO, COMISSAO) VALUES (350,'GAFNEY', 84,'ATEND', 5, CAST(1300.00 AS DECIMAL(10, 2)), NULL);
